import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Menu from "./components/Menu/Menu";
import useStyle from "./styles/useStyles";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const menuLinks = {
    links: [
      { label: "Contacto", link: "#", icon: "house" },
      { label: "Créditos", link: "#", icon: "map" },
      { label: "Quienes somos", link: "#", icon: "map" },
      { label: "Niñeces mapeando", link: "#", icon: "map" },
    ],
  };

  const { COLORS, TYPOGRAPHYS } = useStyle();

  return (
    <html lang="en">
      <body className={inter.className}>
        <header>
          <Menu links={menuLinks.links} />
        </header>
        {children}
        <footer
          className="footer"
          style={{
            backgroundColor: COLORS.main,
            width: "100%",
            height: "8rem",
            marginTop: "5rem",
          }}
        ></footer>
      </body>
    </html>
  );
}
